services:
  app:
    build: .
    container_name: user_management_app
    image: user_management_app:latest
    restart: always
    init: true
    ports:
      - "${PORT}:8000"
    env_file:
      - .env
    entrypoint: ["go", "run", "src/cmd/main.go"]
    volumes:
      - .:/app

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.2
    container_name: user_management_elasticsearch
    environment:
      ES_JAVA_OPTS: "-Xmx384m -Xms384m"
      discovery.type: single-node
      network.host: 0.0.0.0
      xpack.license.self_generated.type: basic
      xpack.security.enabled: false
      xpack.security.transport.ssl.enabled: false
      xpack.security.http.ssl.enabled: false
      ingest.geoip.downloader.enabled: false
      cluster.routing.allocation.disk.threshold_enabled: false

    ports:
      - "9200:9200"

    volumes:
      - .local/elastic:/usr/share/elasticsearch/data

  kibana:
    image: kibana:8.14.1
    container_name: user_management_kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

    volumes:
      - .local/kibana:/usr/share/elasticsearch/data
